spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
#  cloud:
#    config:
#      enabled: false
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8004
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.Oracle12cDialect
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      loanServiceCB:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  timelimiter:
    instances:
      loanServiceCB:
        timeoutDuration: 3s
