spring:
  application:
    name: credit-card-service # Must match FeignClient name in API Gateway
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/CARD_PDB # Your database URL
    username: CARD_MS # Your database username
    password: card123 # Your database password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  security: # <--- ADD THIS SECTION FOR SECURITY CONFIGURATION
    oauth2:
      resourceserver:
        jwt:
          # This is the URL where Keycloak exposes its public keys (JWKS endpoint).
          # Spring Security will use this to validate the signature of incoming JWTs.
          # Replace 8080 with your Keycloak port, bank-realm with your realm name.
          jwk-set-uri: http://localhost:8080/realms/bank-realm/protocol/openid-connect/certs
          # Alternatively, you can use issuer-uri if you prefer. Spring will discover JWKS from here.
          # issuer-uri: http://localhost:8080/realms/bank-realm

server:
  port: 8005 # Card Service typically runs on port 8005

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
      io.github.resilience4j: DEBUG # Enable Resilience4j logging
      org.springframework.security: DEBUG # Enable detailed Spring Security logging
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG # Log incoming requests
      org.hibernate.SQL: DEBUG # Log Hibernate generated SQL
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Log SQL parameter binding

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

resilience4j:
  circuitbreaker:
    configs:
      default: # Default configuration for all circuit breakers
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.client.HttpClientErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
        ignoreExceptions:
          - com.creditcardservice.exceptions.ResourceNotFoundException
          - com.creditcardservice.exceptions.CardServiceException
    instances:
      transactionService:
        baseConfig: default
      accountService:
        baseConfig: default
      userService:
        baseConfig: default

  retry:
    configs:
      default: # Default retry configuration
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - org.springframework.web.client.HttpClientErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.HttpServerErrorException
        ignoreExceptions:
          - com.creditcardservice.exceptions.ResourceNotFoundException
          - com.creditcardservice.exceptions.CardServiceException
    instances:
      transactionService:
        baseConfig: default
      accountService:
        baseConfig: default
      userService:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      transactionService:
        baseConfig: default
      accountService:
        baseConfig: default
      userService:
        baseConfig: default

# Prometheus and Actuator Management Configuration
management:
  tracing: # Existing tracing configuration for Sleuth/Micrometer
    sampling:
      probability: 1.0
