server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/S4N1DHY4/bank-config-repo
          clone-on-start: true
          default-label: main
  application:
    name: config-server

