server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/S4N1DHY4/bank-config-repo
          clone-on-start: true
          default-label: main
  application:
    name: config-server

management:
  tracing:
    sampling:
      probability: 1.0
     
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"